### ISSUE TITLE
Weekday repeats - shows "Sun" where it should show "Mon"

### ISSUE THREAD

**Issue by juergenspecht** [bljohnsondev/mishos#10]
Hi there, thanks for Mishos, a really great product I just discovered! 

One minor cosmetic thing: The weekdays function seem to have a glitch, it doubles "Sun" as in: it shows "Sun" where it should show "Mon" in the Upcoming function. See screenshot.
![mishos-dates](https://github.com/user-attachments/assets/cebc3474-105c-4b32-9764-4ff52c376400)

Thanks again!

**Comment by juergenspecht** [comment]
Thanks for the fast response! Sorry, I didn't provide enough information! My local timezone is `Europe/Berlin` and the shows are: Lioness, FROM, Dune: Prophecy, Silo, see also attachment.
![mishos2](https://github.com/user-attachments/assets/176f70ef-9729-4b94-9bdd-35c843828379)

**Comment by bljohnsondev** [comment]
Thanks!  I'll take a look.

**Comment by bljohnsondev** [comment]
I'm pretty sure this was indeed a timezone issue.  I fixed it but I haven't deployed the change yet.  I'm testing this using your timezone so I need to confirm a couple things.

First, ignoring the week day issue, were the air times displayed actually correct or were they totally wrong?

For example, in your screenshot it says that the next Dune: Prophecy episode aired on Nov 25th at 8PM?  Is that correct or should that actually have been Nov 25 at 3AM?

Silo says it airs on Nov 27th at 6am but this should probably show 1PM instead (because the TVMaze defaults to 12PM GMT for shows with no specified air time and Europe/Berlin is GMT+1).

So you definitely found a bug with the week day being incorrect but I think you may have helped me actually track down a bigger issue with incorrect air times in general :smile:

Let me know if this sounds correct and if so I'll deploy the change.

Thanks for your assistance!

**Comment by juergenspecht** [comment]
Hi there, thanks for looking into it!

The `Air Times` are basically wrong, but that’s hard to guess because they don't show in which timezone :)

I found another source for the "correct" Air Time for example for the next `Silo` Show `S02E03`, which should be `9am` in CET and I don't find any `6am` mentioned there. Have a look here:

<img width="564" alt="SCR-20241126-hxvz" src="https://github.com/user-attachments/assets/adbc3fc0-2455-4c41-9f04-0711ffaf68a2">

I haven't looked into the TVMaze API yet to see what they provide for this specific show, sorry.

So yes, I believe the calculation is wrong and are happy to test your fix! 

Thanks again!

**Comment by juergenspecht** [comment]
ah, sorry, the source is: https://www.sportskeeda.com/us/shows/silo-season-2-episode-3-release-date-time-watch-recap

**Comment by juergenspecht** [comment]
Ok, have a look here: https://api.tvmaze.com/episodes/2957755

```{"id":2957755,"url":"https://www.tvmaze.com/episodes/2957755/silo-2x03-solo","name":"Solo","season":2,"number":3,"type":"regular","airdate":"2024-11-27","airtime":"","airstamp":"2024-11-27T12:00:00+00:00","runtime":54,"rating":{"average":null},"image":null,"summary":"<p>Bernard turns to Judge Meadows for help. Billings begins to wonder if he's being lied to. Juliette finally meets the man in the vault.</p>","_links":{"self":{"href":"https://api.tvmaze.com/episodes/2957755"},"show":{"href":"https://api.tvmaze.com/shows/38052","name":"Silo"}}}```

`airtime` is empty, so it should default to `00:00` on `2024-11-27`. Current Mishos with `Europe/Berlin` shows `6am`

**Comment by bljohnsondev** [comment]
> `airtime` is empty, so it should default to `00:00` on `2024-11-27`. Current Mishos with `Europe/Berlin` shows `6am`

Right.  For streaming shows with no specific published air time TVMaze defaults to "12:00:00" which is 12PM (GMT).  Europe/Berlin is GMT+1 so this should actually show as 1PM rather than 6AM.  In that Silo example it shows `"airstamp":"2024-11-27T12:00:00+00:00"`

If you check the next Dune: Prophecy episode: [https://api.tvmaze.com/episodes/3031114](https://api.tvmaze.com/episodes/3031114)

It shows the air date as `"airstamp":"2024-12-02T02:00:00+00:00"`

So with GMT+1 this should be 3AM for you, right?

**Comment by bljohnsondev** [comment]
I merged a fix for this issue but keeping it open until you get a chance to confirm it's fixed for you.

I've pushed the fix to the latest docker image (or as `bljohnsondev/mishos:v0.2.12` if you prefer the pinned versions).

Let me know if it works and if so I'll close the issue.

**Comment by ghost** [comment]
Ok, I just updated and can confirm it's now correct! Thanks again for this project, it's really useful and looks nice!

 Keep up the great work and you can close this issue! 
 
 👋

**Comment by bljohnsondev** [comment]
Awesome!  Thanks for your assistance in helping me track down this issue and for your kind words.  Glad you like it!  If you have any other issues let me know.
